language: generic

notifications:
    email: false

branches:
    only:
        - master
matrix:
    include:
        - env: TARGET=projects/projectA
        - env: TARGET=projects/projectB

script: if .travis/build-condition.sh $TRAVIS_COMMIT_RANGE $TARGET; then echo "$TARGET is being built" && cd $TARGET && npm install && npm run test; else echo "$TARGET is NOT being built"; fi
